#!/bin/bash
#SBATCH --job-name=downloadSRR # Job name
#SBATCH --mail-type=END,FAIL # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=st4302@nyu.edu # Where to send mail
#SBATCH --ntasks=1 # Run on a single node
#SBATCH --mem=8gb # Job memory request
#SBATCH --time=02:00:00 # Time limit hrs:min:sec
#SBATCH --output=SRR_%j.log # Standard output and error log
#SBATCH -p cpu_short # Specifies location to submit job

SRR=$1

module load sratoolkit/2.9.1
module load fastqc/0.11.7 # load module

# Run fastq-dump to download specified file from the SRA
fastq-dump --split-files ${SRR} --gzip -O /gpfs/scratch/tianos01/applied_seq/assignment1_NGS/ --origfmt

#Run fastqc
fastqc -o /gpfs/scratch/tianos01/applied_seq/assignment1_NGS/ /gpfs/scratch/tianos01/applied_seq/assignment1_NGS/${SRR}_1.fastq.gz /gpfs/scratch/tianos01/applied_seq/assignment1_NGS/${SRR}_2.fastq.gz