#!/bin/bash
#SBATCH -job-name=trim # Job name
#SBATCH --mail-type=END,FAIL # Mail events (NONE, BEGIN, END, FAIL, ALL)
#SBATCH --mail-user=st4302@nyu.edu # Where to send mail
#SBATCH --ntasks=1 # Run on a single node
#SBATCH --mem=8gb # Job memory request
#SBATCH --time=02:00:00 # Time limit hrs:min:sec
#SBATCH --output=Trim_%j.log # Standard output and error log
#SBATCH -p cpu_short # Specifies location to submit job

FNAME=$1

#Load modules

module load trimgalore/0.5.0
module load python/cpu/2.7.15-ES

trim_galore --paired ${FNAME}_1.fastq.gz ${FNAME}_2.fastq.gz --fastqc --fastqc_args "-o /gpfs/scratch/tianos01/applied_seq/assignment1_NGS" --q 30 --gzip